[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:sync]
command=/sync.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:server]
command=/init.sh
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0
redirect_stderr=true